require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4
